import React from "react";
import Head from "next/head";
import CustomCard from "@/components/CustomCard";

const Home = () => {
  return (
    <>
      <Head>
        <title>Radhe Enterprise</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/re.png" />
      </Head>
    </>
  );
};

export default Home;
